services:
  zoo:
    image: zookeeper:latest
    container_name: zookeeper_servico
    ports:
      - "2181:2181"
    networks:
      - email-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_servico
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - email-net
    depends_on:
      - zoo

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_servico
    ports:
      - "1025:1025" 
      - "8025:8025" 
    networks:
      - email-net

  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "5000:5000"
    networks:
      - email-net
    depends_on:
      - zoo
      - rabbitmq

  consumer:
    build: ./consumer
    networks:
      - email-net
    depends_on:
      rabbitmq:
        condition: service_started
      mailhog:
        condition: service_started
    deploy:
      replicas: 3

  frontend:
    build: ./frontend
    container_name: frontend_web
    ports:
      - "8080:8080"
    networks:
      - email-net
    depends_on:
      - backend

networks:
  email-net:
    driver: bridge