services:
  zoo:
    image: zookeeper:latest
    container_name: zookeeper_servico
    ports:
      - "2181:2181"
    networks:
      - email-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_servico
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - email-net
    depends_on:
      - zoo

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_servico
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - email-net

  backend:
    build: ./backend
    networks:
      - email-net
    depends_on:
      zoo:
        condition: service_started
      rabbitmq:
        condition: service_started
    deploy:
      replicas: 3

  consumer:
    build: ./consumer
    networks:
      - email-net
    depends_on:
      rabbitmq:
        condition: service_started
      mailhog:
        condition: service_started
    deploy:
      replicas: 3

  frontend:
    build: ./frontend
    networks:
      - email-net
    depends_on:
      backend:
        condition: service_started
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - email-net
    depends_on:
      - frontend
      - backend

networks:
  email-net:
    driver: bridge